version: '2'

services:

    docker-1:
        image: docker:1.11-dind
        restart: always
        tty: true
        privileged: true
        dns:
            - 8.8.8.8
            - 8.8.4.4
        command: [
            '--log-level', 'debug',
            '--storage-driver', 'overlay',
            '--cluster-store', 'consul://cluster-store:8500',
            '--cluster-advertise', 'eth0:2375',
        ]
    docker-2:
        extends:
            service: docker-1
    docker-3:
        extends:
            service: docker-1

    swarm:
        image: swarm
        restart: always
        command: [
            'manage',
            'docker-1:2375,docker-2:2375,docker-3:2375',
            #'consul://cluster-store:8500',
        ]

    cluster-store:
        image: consul
        restart: always
        command: [
            'agent',
            '-dev',
            '-client', '0.0.0.0',
        ]
